import type { Finding, ExistingComment, CodeHubIssue } from './types.js';
import type { CodeHubClient } from './codehub-client.js';
import { deduplicateFindings } from './post-processor.js';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

const SUMMARY_MARKER = '<!-- code-review:summary -->';
const FINDING_MARKER = '<!-- code-review:finding -->';

export interface CodeHubPublishOptions {
  mrIid: number;
  client: CodeHubClient;
  findings: Finding[];
  dryRun?: boolean;
  deduplicate?: boolean;
  language?: string;
  baseSha?: string;
  headSha?: string;
  startSha?: string;
}

export interface CodeHubPublishResult {
  ok: boolean;
  summaryCreated: boolean;
  summaryCommentId?: number;
  findingComments: Array<{
    id: number;
    finding: Finding;
  }>;
  skippedFindings: Finding[];
  totalFindings: number;
  publishedCount: number;
  skippedCount: number;
  error?: string;
}

function formatFindingMarkdown(finding: Finding, language = 'zh-CN'): string {
  const severityEmoji: Record<string, string> = {
    critical: '🔴',
    high: '🟠',
    medium: '🟡',
    low: '🔵',
    info: '⚪',
  };
  const emoji = severityEmoji[finding.severity] ?? '⚪';
  const sevLabel = finding.severity.toUpperCase();

  const lines: string[] = [];
  lines.push(`${FINDING_MARKER}`);
  lines.push(`### ${emoji} [${sevLabel}] ${finding.message.split('\n')[0].slice(0, 80)}`);
  lines.push('');
  lines.push(`**文件:** \`${finding.file}\``);
  if (finding.line) {
    lines.push(`**行号:** ${finding.line}`);
  }
  lines.push('');
  lines.push(`**${language === 'zh-CN' ? '描述' : 'Description'}:**`);
  lines.push(finding.message);
  lines.push('');
  if (finding.suggestion) {
    lines.push(`**${language === 'zh-CN' ? '建议' : 'Suggestion'}:**`);
    lines.push(finding.suggestion);
    lines.push('');
  }
  if (finding.ruleId) {
    lines.push(`<sub>${language === 'zh-CN' ? '规则' : 'Rule'}: ${finding.ruleId}</sub>`);
  }

  return lines.join('\n');
}

function formatSummaryMarkdown(
  findings: Finding[],
  language = 'zh-CN',
): string {
  const severityOrder: Array<'critical' | 'high' | 'medium' | 'low' | 'info'> = [
    'critical',
    'high',
    'medium',
    'low',
    'info',
  ];
  const countBySeverity: Record<string, number> = {};
  for (const f of findings) {
    countBySeverity[f.severity] = (countBySeverity[f.severity] ?? 0) + 1;
  }

  const lines: string[] = [];
  lines.push(SUMMARY_MARKER);
  lines.push(`## ${language === 'zh-CN' ? '🤖 代码审查报告' : '🤖 Code Review Report'}`);
  lines.push('');
  lines.push(`> ${language === 'zh-CN' ? '本报告由 OpenCode 代码审查工具自动生成' : 'This report is generated by OpenCode code review tool'}`);
  lines.push('');

  lines.push(`### ${language === 'zh-CN' ? '统计概览' : 'Summary'}`);
  lines.push('');
  lines.push(`| ${language === 'zh-CN' ? '严重级别' : 'Severity'} | ${language === 'zh-CN' ? '数量' : 'Count'} |`);
  lines.push('| --- | --- |');
  for (const sev of severityOrder) {
    const count = countBySeverity[sev] ?? 0;
    const label = sev.toUpperCase();
    lines.push(`| ${label} | ${count} |`);
  }
  lines.push(`| **${language === 'zh-CN' ? '总计' : 'Total'}** | **${findings.length}** |`);
  lines.push('');

  if (findings.length > 0) {
    lines.push(`### ${language === 'zh-CN' ? '问题列表' : 'Issue List'}`);
    lines.push('');
    const files = [...new Set(findings.map((f) => f.file))];
    for (const file of files) {
      lines.push(`- **\`${file}\`**`);
      const fileFindings = findings.filter((f) => f.file === file);
      for (const f of fileFindings) {
        const lineInfo = f.line ? `:${f.line}` : '';
        lines.push(`  - [${f.severity.toUpperCase()}] ${f.message.split('\n')[0].slice(0, 50)} (\`${file}${lineInfo}\`)`);
      }
    }
    lines.push('');
  } else {
    lines.push(`### ✅ ${language === 'zh-CN' ? '未发现问题' : 'No Issues Found'}`);
    lines.push('');
    lines.push(language === 'zh-CN' ? '代码看起来不错！未发现明显问题。' : 'Code looks good! No obvious issues found.');
    lines.push('');
  }

  return lines.join('\n');
}

export async function publishFindingsToCodeHub(
  options: CodeHubPublishOptions,
): Promise<CodeHubPublishResult> {
  const {
    mrIid,
    client,
    findings,
    dryRun = false,
    deduplicate = true,
    language = 'zh-CN',
    baseSha,
    headSha,
    startSha,
  } = options;

  const result: CodeHubPublishResult = {
    ok: true,
    summaryCreated: false,
    findingComments: [],
    skippedFindings: [],
    totalFindings: findings.length,
    publishedCount: 0,
    skippedCount: 0,
  };

  let findingsToPublish = findings;
  if (deduplicate) {
    try {
      const existingComments = await fetchExistingCodeHubComments(mrIid, client);
      const deduped = deduplicateFindings(findings, existingComments);
      result.skippedFindings = findings.filter((f) => !deduped.includes(f));
      result.skippedCount = result.skippedFindings.length;
      findingsToPublish = deduped;
    } catch {
      findingsToPublish = findings;
    }
  }

  if (dryRun) {
    result.publishedCount = findingsToPublish.length;
    result.summaryCreated = true;
    return result;
  }

  try {
    const summaryBody = formatSummaryMarkdown(findings, language);
    const summaryComment = await client.createMRComment(mrIid, summaryBody);
    result.summaryCreated = true;
    result.summaryCommentId = summaryComment.id;
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    result.ok = false;
    result.error = `Failed to create summary comment: ${message}`;
  }

  for (const finding of findingsToPublish) {
    try {
      const body = formatFindingMarkdown(finding, language);
      const comment = await client.createMRComment(mrIid, body, {
        path: finding.file,
        line: finding.line,
        lineType: 'new',
        baseSha,
        headSha,
        startSha,
      });
      result.findingComments.push({ id: comment.id, finding });
      result.publishedCount++;
    } catch {
      result.skippedFindings.push(finding);
      result.skippedCount++;
    }
  }

  return result;
}

export async function fetchExistingCodeHubComments(
  mrIid: number,
  client: CodeHubClient,
): Promise<ExistingComment[]> {
  try {
    const comments = await client.getMRComments(mrIid);
    return comments
      .filter((c) => c.body?.includes(FINDING_MARKER) || c.body?.includes(SUMMARY_MARKER))
      .map((c) => ({
        file: c.position?.new_path ?? c.position?.old_path ?? '',
        line: c.position?.new_line ?? c.position?.old_line ?? 0,
        body: c.body ?? '',
      }));
  } catch {
    return [];
  }
}

export class CodeHubCommentPublisher {
  private readonly client: CodeHubClient;
  private readonly mrIid: number;

  constructor(client: CodeHubClient, mrIid: number) {
    this.client = client;
    this.mrIid = mrIid;
  }

  async publish(
    findings: Finding[],
    options?: {
      dryRun?: boolean;
      deduplicate?: boolean;
      language?: string;
      baseSha?: string;
      headSha?: string;
      startSha?: string;
    },
  ): Promise<CodeHubPublishResult> {
    return publishFindingsToCodeHub({
      mrIid: this.mrIid,
      client: this.client,
      findings,
      ...options,
    });
  }

  async getExistingComments(): Promise<ExistingComment[]> {
    return fetchExistingCodeHubComments(this.mrIid, this.client);
  }
}

/**
 * 生成完整的 Markdown 审查报告（用于保存文件和提 Issue）
 */
function formatFullReport(
  findings: Finding[],
  options?: { mrTitle?: string; mrIid?: number; language?: string },
): string {
  const language = options?.language ?? 'zh-CN';
  const isZh = language === 'zh-CN';
  const severityOrder: Array<'critical' | 'high' | 'medium' | 'low' | 'info'> = [
    'critical',
    'high',
    'medium',
    'low',
    'info',
  ];
  const severityEmoji: Record<string, string> = {
    critical: '🔴',
    high: '🟠',
    medium: '🟡',
    low: '🔵',
    info: '⚪',
  };

  const countBySeverity: Record<string, number> = {};
  for (const f of findings) {
    countBySeverity[f.severity] = (countBySeverity[f.severity] ?? 0) + 1;
  }

  const lines: string[] = [];
  const title = options?.mrTitle
    ? `${options.mrTitle} (MR !${options.mrIid ?? '-'})`
    : `MR !${options?.mrIid ?? '-'}`;

  lines.push(`# ${isZh ? '🤖 代码审查报告' : '🤖 Code Review Report'} - ${title}`);
  lines.push('');
  lines.push(`> ${isZh ? '本报告由 OpenCode 代码审查工具自动生成' : 'This report is generated by OpenCode code review tool'}`);
  lines.push('');
  lines.push(`- **${isZh ? '生成时间' : 'Generated At'}:** ${new Date().toISOString()}`);
  lines.push(`- **${isZh ? '问题总数' : 'Total Findings'}:** ${findings.length}`);
  lines.push('');

  lines.push(`## ${isZh ? '统计概览' : 'Summary'}`);
  lines.push('');
  lines.push(`| ${isZh ? '严重级别' : 'Severity'} | ${isZh ? '数量' : 'Count'} |`);
  lines.push('| --- | --- |');
  for (const sev of severityOrder) {
    const count = countBySeverity[sev] ?? 0;
    const emoji = severityEmoji[sev] ?? '';
    lines.push(`| ${emoji} ${sev.toUpperCase()} | ${count} |`);
  }
  lines.push(`| **${isZh ? '总计' : 'Total'}** | **${findings.length}** |`);
  lines.push('');

  if (findings.length === 0) {
    lines.push(`## ✅ ${isZh ? '未发现问题' : 'No Issues Found'}`);
    lines.push('');
    lines.push(isZh ? '代码看起来不错！未发现明显问题。' : 'Code looks good! No obvious issues found.');
    lines.push('');
    return lines.join('\n');
  }

  lines.push(`## ${isZh ? '问题列表' : 'Issue List'}`);
  lines.push('');
  const files = [...new Set(findings.map((f) => f.file))];
  for (const file of files) {
    const fileFindings = findings.filter((f) => f.file === file);
    lines.push(`### \`${file}\` (${fileFindings.length})`);
    lines.push('');
    for (const f of fileFindings) {
      const emoji = severityEmoji[f.severity] ?? '⚪';
      const lineInfo = f.line ? `:${f.line}` : '';
      lines.push(`#### ${emoji} [${f.severity.toUpperCase()}] ${f.message.split('\n')[0].slice(0, 80)}`);
      lines.push('');
      lines.push(`- **${isZh ? '位置' : 'Location'}:** \`${file}${lineInfo}\``);
      if (f.ruleId) {
        lines.push(`- **${isZh ? '规则' : 'Rule'}:** \`${f.ruleId}\``);
      }
      lines.push('');
      lines.push(`**${isZh ? '描述' : 'Description'}:**`);
      lines.push('');
      lines.push(f.message);
      lines.push('');
      if (f.suggestion) {
        lines.push(`**${isZh ? '建议' : 'Suggestion'}:**`);
        lines.push('');
        lines.push(f.suggestion);
        lines.push('');
      }
      lines.push('---');
      lines.push('');
    }
  }

  return lines.join('\n');
}

/**
 * 将检视报告保存为 Markdown 文件
 */
export async function saveReportToFile(
  findings: Finding[],
  filePath: string,
  options?: { mrTitle?: string; mrIid?: number; language?: string },
): Promise<void> {
  const report = formatFullReport(findings, options);
  const dir = dirname(filePath);
  if (dir) {
    mkdirSync(dir, { recursive: true });
  }
  writeFileSync(filePath, report, 'utf-8');
}

/**
 * 将检视结果一键提为 CodeHub Issue
 */
export async function publishFindingsAsIssue(options: {
  client: CodeHubClient;
  findings: Finding[];
  mrIid?: number;
  mrTitle?: string;
  language?: string;
  labels?: string[];
}): Promise<{ ok: boolean; issue?: CodeHubIssue; error?: string }> {
  try {
    const title = `[代码审查] ${options.mrTitle ?? `MR !${options.mrIid}`} - ${options.findings.length} 个问题`;
    const description = formatFullReport(options.findings, {
      mrIid: options.mrIid,
      mrTitle: options.mrTitle,
      language: options.language,
    });
    const issue = await options.client.createIssue({
      title,
      description,
      labels: options.labels ?? ['code-review'],
    });
    return { ok: true, issue };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return { ok: false, error: message };
  }
}
